# Generated by Django 5.0.4 on 2026-04-10 09:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalDelegate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delegate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegated_from', to=settings.AUTH_USER_MODEL)),
                ('delegator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegated_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('SUBMITTED', 'Submitted for Review'), ('APPROVED_L1', 'Approved (Level 1)'), ('REJECTED_L1', 'Rejected (Level 1)'), ('APPROVED_L2', 'Approved (Level 2)'), ('REJECTED_L2', 'Rejected (Level 2)'), ('PAYMENT_PROCESSED', 'Payment Processed'), ('PAYMENT_COMPLETED', 'Payment Completed'), ('RETIREMENT_SUBMITTED', 'Retirement Submitted'), ('RETIREMENT_APPROVED', 'Retirement Approved'), ('RETIREMENT_RETURNED', 'Returned for Correction'), ('CLOSED', 'Request Closed'), ('CANCELLED', 'Request Cancelled'), ('AMOUNT_ADJUSTED', 'Amount Adjusted')], max_length=30)),
                ('previous_status', models.CharField(blank=True, max_length=30)),
                ('new_status', models.CharField(blank=True, max_length=30)),
                ('remarks', models.TextField(blank=True)),
                ('amount_at_action', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_actions', to='payments.paymentrequest')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['request', 'timestamp'], name='approvals_a_request_ff2ced_idx'), models.Index(fields=['actor', 'timestamp'], name='approvals_a_actor_i_1f5b38_idx'), models.Index(fields=['action'], name='approvals_a_action_ac849b_idx')],
            },
        ),
    ]
