# Generated by Django 5.0.4 on 2026-04-10 09:50

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('requires_additional_docs', models.BooleanField(default=False)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Payment Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('amount_approved', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('amount_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('purpose', models.TextField()),
                ('beneficiary_name', models.CharField(blank=True, max_length=200)),
                ('beneficiary_account', models.CharField(blank=True, max_length=50)),
                ('beneficiary_bank', models.CharField(blank=True, max_length=100)),
                ('payment_method', models.CharField(default='Bank Transfer', max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW1', 'Under Review (Level 1)'), ('APPROVED_L1', 'Approved by Supervisor'), ('REJECTED_L1', 'Rejected by Supervisor'), ('UNDER_REVIEW2', 'Under Review (Level 2)'), ('APPROVED_L2', 'Approved by Finance Controller'), ('REJECTED_L2', 'Rejected by Finance Controller'), ('PROCESSING', 'Finance Processing'), ('PAID', 'Payment Completed'), ('RETIREMENT_PENDING', 'Awaiting Retirement'), ('RETIREMENT_SUBMITTED', 'Retirement Submitted'), ('RETIREMENT_APPROVED', 'Retirement Approved'), ('RETIREMENT_REJECTED', 'Retirement Correction Needed'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=30)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('needed_by_date', models.DateField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('is_advance_payment', models.BooleanField(default=False)),
                ('has_retirement', models.BooleanField(default=False)),
                ('retirement_deadline', models.DateField(blank=True, null=True)),
                ('data_hash', models.CharField(blank=True, max_length=64)),
                ('auditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_requests', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payments.paymentcategory')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_requests', to='accounts.department')),
                ('finance_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_requests', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewer1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review1_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewer2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review2_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('can_view_all_requests', 'Can view all payment requests'), ('can_export_reports', 'Can export reports')],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment_type', models.CharField(choices=[('GENERAL', 'General'), ('APPROVAL', 'Approval Note'), ('REJECTION', 'Rejection Reason'), ('QUERY', 'Query'), ('SYSTEM', 'System Message')], default='GENERAL', max_length=15)),
                ('content', models.TextField()),
                ('is_internal', models.BooleanField(default=False, help_text='Internal notes not visible to requester')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='payments.paymentrequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('SUPPORTING', 'Supporting Document'), ('QUOTE', 'Quotation'), ('INVOICE', 'Invoice'), ('RECEIPT', 'Receipt'), ('CONTRACT', 'Contract'), ('OTHER', 'Other')], default='SUPPORTING', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='payment_docs/%Y/%m/')),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_retirement_doc', models.BooleanField(default=False)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='payments.paymentrequest')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='paymentrequest',
            index=models.Index(fields=['status'], name='payments_pa_status_363ec6_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrequest',
            index=models.Index(fields=['requester'], name='payments_pa_request_4ab918_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrequest',
            index=models.Index(fields=['department'], name='payments_pa_departm_da3107_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrequest',
            index=models.Index(fields=['request_number'], name='payments_pa_request_527133_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrequest',
            index=models.Index(fields=['created_at'], name='payments_pa_created_a76cc7_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrequest',
            index=models.Index(fields=['priority', 'status'], name='payments_pa_priorit_317b85_idx'),
        ),
    ]
