# Generated by Django 5.0.4 on 2026-04-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestdocument',
            name='file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
